## FrozenLake-v0 using Q-Learning

In [3]:
import gym
import numpy as np
import time
import random
from IPython.display import clear_output

In [2]:
env=gym.make("FrozenLake-v0")

In [5]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001



In [7]:
rewards_all_episodes=[]
for episode in range(num_episodes):
    done=False
    rewards_current_episode=0
    state=env.reset()
    
    for step in range(max_steps_per_episode):
        ran=random.uniform(0,1)
        if ran > exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
        new_state,reward,done,info=env.step(action)
        q_table[state,action]=((1-learning_rate)*q_table[state,action])+(learning_rate*(reward+discount_rate*np.max(q_table[new_state,:])))
        state=new_state
        rewards_current_episode+=reward
        if done==True:
            break
            
    exploration_rate=(min_exploration_rate)+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.03900000000000003
2000 :  0.19800000000000015
3000 :  0.4150000000000003
4000 :  0.5560000000000004
5000 :  0.6520000000000005
6000 :  0.6540000000000005
7000 :  0.6650000000000005
8000 :  0.6730000000000005
9000 :  0.7020000000000005
10000 :  0.6940000000000005


********Q-table********

[[0.55164412 0.4818897  0.50762114 0.48885938]
 [0.27756013 0.2502388  0.38723351 0.48184268]
 [0.41137328 0.41554762 0.38692506 0.45822402]
 [0.28583456 0.17898868 0.33052528 0.4376012 ]
 [0.58060887 0.37144253 0.44291604 0.3428784 ]
 [0.         0.         0.         0.        ]
 [0.16539357 0.16187488 0.33288429 0.15401945]
 [0.         0.         0.         0.        ]
 [0.34024375 0.34873552 0.34928448 0.61157793]
 [0.38408345 0.65781818 0.35237551 0.42429115]
 [0.58564977 0.40682247 0.21773774 0.29862217]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45851287 0.55787441 0.78231547 

In [8]:
for episode in range(3):
    state=env.reset()
    done=False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action=np.argmax(q_table[state,:])
        new_state,reward,done,info=env.step(action)
        if done==True:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("****You reached the goal!****")
                time.sleep(3)
                clear_output(wait=True)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state=new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
